name: luacheck

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    luacheck:
        runs-on: codeberg-tiny

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: true
            - name: Install required packages
              run: apt update && apt upgrade -y && apt install luarocks -y
            - name: Install luacheck through luarocks
              run: luarocks install luacheck
            - name: Luacheck everything
              run: find . -iname '*.lua' | xargs luacheck --max-line-length 120
